trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: net35
    displayName: "Build .NET 3.5"
    dependsOn: []
    jobs:
    - job: Build
      displayName: "Build .NET 3.5"
      steps:

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'e85054ec-30a9-40de-84e4-6bc054914bbe'
          definition: '2'
          buildVersionToDownload: 'latest'
          targetPath: '$(Pipeline.Workspace)'

      - task: PowerShell@2
        inputs:
          filePath: '$(Pipeline.Workspace)/RoslynObfuscator/RoslynObfuscator.ps1'
          arguments: '-SlnFile Rubeus/Rubeus.sln'
          failOnStderr: true

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: '/p:TargetFrameworkVersion=v3.5'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: 'Rubeus/bin/Release/Rubeus.exe'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true
          
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Rubeus-net3.5'
          publishLocation: 'Container'
          

  - stage: net40
    displayName: "Build .NET 4.0"
    dependsOn: []
    jobs:
    - job: Build
      displayName: "Build .NET 4.0"
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'e85054ec-30a9-40de-84e4-6bc054914bbe'
          definition: '2'
          buildVersionToDownload: 'latest'
          targetPath: '$(Pipeline.Workspace)'

      - task: PowerShell@2
        inputs:
          filePath: '$(Pipeline.Workspace)/RoslynObfuscator/RoslynObfuscator.ps1'
          arguments: '-SlnFile Rubeus/Rubeus.sln'
          failOnStderr: true
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: '/p:TargetFrameworkVersion=v4.6.1'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: 'Rubeus/bin/Release/Rubeus.exe'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Rubeus-net4.0'
          publishLocation: 'Container'
